### ISSUE TITLE
Avogadro2 Plugin NOT Recognizing Imports

### ISSUE THREAD

**Issue by Dfilono** [Dfilono/Molecule-Builder#4]
The code is crashing in Avogadro2 whenever I need to reference a function within the code base. While I am not sure of the EXACT error, I believe the error is that the function and/or package is not being found. I tried installing the package via the following:

```
git clone https://github.com/Dfilono/Molecule-Builder
cd Molecule-Builder
pip install .
```

This does not seem to make a difference. If I import the code as currently uploaded to the repo like the following:

```
import moleculeBuilder as MB
```

Avogadro2 recognizes this. However, if I import the code the following way:

```
from moleculeBuilder import drawMol, readWriteFiles, defaultParams
```

Avogadro2 no longer recognizes the plugin at all. I'm unsure if the import method makes a difference, however since the first method is not functioning I don't know if finding a way to switch to the second would solve the problem (since in theory they are the same). 

I've also attempted this without the package being explicitly installed via pip, with the imports referencing just the local code itself. Unfortunately this has the same result.

The files being referenced in this error are [plugin.json](https://github.com/Dfilono/Molecule-Builder/blob/main/plugin.json) and [fillBox.py](https://github.com/Dfilono/Molecule-Builder/blob/main/moleculeBuilder/avogadroPlugin/fillBox.py)

**Comment by ghutchis** [comment]
When you say "crashing" - the plugin doesn't run, or Avogadro GUI crashes?

I'm not enough of a Python expert to know why the two different import statements are working differently. I'd go with what works for now.

**Comment by ghutchis** [comment]
It would also help to know if there's any sort of error from the script.

**Comment by Dfilono** [comment]
Part of it turned out to be a package issue. My setup.py file and __init__.py files weren't entirely setup correctly. The script still isn't finishing so I am leaving the issue open, but I am investigating what the current issue is.
